version: "3.9"  # optional since v1.27.0
services:
  influx:
    image: influxdb:2.0.8-alpine
    environment:
    - DOCKER_INFLUXDB_INIT_USERNAME=pulu 
    - DOCKER_INFLUXDB_INIT_PASSWORD=pulu
    - DOCKER_INFLUXDB_INIT_ORG=my-org 
    - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket 
    ports:
    - 8086:8086
    restart: unless-stopped
  mongo:
    image: mongo
    ports:
    - 27017:27017
    restart: unless-stopped
  frontend:
    image: ghcr.io/vives-projectwerk-2021/vue-frontend:latest
    ports:
    - 8080:80
  proxy:
    image: nginx
    links:
    - frontend
    ports:
    - 80:80
  backend: 
    image: ghcr.io/vives-projectwerk-2021/backend:latest
    ports:
    - 3000:3000
  ttn:
    image: ghcr.io/vives-projectwerk-2021/ttn-listener:latest
    environment:
    - MQTT_USERNAME=pulu@ttn
    - MQTT_PASSWORD=NNSXS.R22QD7NLQ5VMWDLN4I5KJHWJHHNJNJKYL4GY5ZA.LZ3F33KIPFJU3AEFEZROJ4YKUTQ3FFFPRFXTX7QCIQOII6TGLIFA
    - BROKER_ADDRESS=eu1.cloud.thethings.network
    - BACKEND_BASE_URL=localhost
    - BACKEND_PORT=3000
