on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Vue-Frontend
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/vives-projectwerk-2021/vue-frontend:latest
          build-args: |
            VUE_APP_WS=${{ secrets.VUE_APP_WS }}
            VUE_APP_BACKEND_BASE_URL=${{ secrets.VUE_APP_BACKEND_BASE_URL }}
	          VUE_APP_MAPBOX_TOKEN=${{ secrets.VUE_APP_MAPBOX_TOKEN }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
