name: staging

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.meta.outputs.version }}
      image: ${{ steps.meta.outputs.tags }}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: ghcr.io/vives-projectwerk-2021/pulu-frontend
        tags: type=ref,event=pr
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VUE_APP_WS=${{ secrets.VUE_APP_WS }}
          VUE_APP_BACKEND_BASE_URL=${{ secrets.VUE_APP_BACKEND_BASE_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_DEPLOY_KEY }}
        known_hosts: 'no-hosts'
    - name: install pulu-cli
      run: |
        curl -L https://github.com/vives-projectwerk-2021/pulu-cli/releases/latest/download/pulu-linux -o /usr/local/bin/pulu
        chmod +x /usr/local/bin/pulu
    - run: |
        pulu exec staging "docker rm -f pulu-frontend.${{ needs.build.outputs.pr }}"
        export PULU_FRONTEND_PORT=$(ruby -e 'require "socket"; puts Addrinfo.tcp("", 0).bind {|s| s.local_address.ip_port }')
        pulu exec staging " \
        docker run -t --name pulu-frontend.${{ needs.build.outputs.pr }} --privileged \
        -v /devops/.ssh/id_rsa:/root/.ssh/id_rsa \
        -v /devops/deployment/staging/.env:/pulu.env \
        -p $PULU_FRONTEND_PORT:8080 \
        -e PULU_FRONTEND="${{ needs.build.outputs.image }}" \
        ghcr.io/vives-projectwerk-2021/pulu-sandbox \
        make production"

        pulu exec staging "docker start pulu-frontend.${{ needs.build.outputs.pr }}"
    - name: Sandbox port
      run: echo $PULU_FRONTEND_PORT